> Currently following resources

[CampusX_PyTorch_Complete](https://www.youtube.com/watch?v=mDsFsnw3SK4&list=PLKnIA16_Rmvboy8bmDCjwNHgTaYH2puK7&index=3)

<hr>
<hr>

## **Intro**

> Latest version of `Pytorch` is `2.10.0` (as of 2026)

`Pytorch` is a popular open-source Deep Learning Library developed by `Facebook's AI Research lab (FAIR)`. In 2002, `Torch` was developed with `Lua` especially for performing `Tesnsor` based computations. In 2016, `Pytorch` was developed as a Python version of `Torch` and it has been widely used in the field of `Deep Learning` since then.

`Pytorch` provides a flexible and dynamic computational graph. 

**Computational Graph** is a way to represent mathematical computations as a graph, where nodes represent operations and edges represent the flow of data. In `Pytorch`, the computational graph is dynamic, which means that it can be modified on-the-fly during runtime. This allows for more flexibility in building and training neural networks, as you can easily change the architecture or the operations being performed without having to redefine the entire graph.

**ONNX(Open Neural Network Exchange)** is an open format for representing machine learning models. It allows models to be transferred between different frameworks, such as `Pytorch`, `TensorFlow`, and `Caffe2`. This means that you can train a model in one framework and then export it to another framework for inference or deployment.

<hr>

### **Core Features of `Pytorch`**

**Tensor Computations**: `Pytorch` provides a powerful and efficient way to perform tensor computations. Tensors are multi-dimensional arrays that can be used to represent data in various forms, such as images, text, and audio. `Pytorch` provides a wide range of operations for manipulating tensors, including mathematical operations, indexing, slicing, and broadcasting.

**Dynamic Computational Graph**: As mentioned earlier, `Pytorch` uses a dynamic computational graph, which allows for more flexibility in building and training neural networks. This means that you can easily change the architecture or the operations being performed without having to redefine the entire graph.

**GPU Acceleration**: `Pytorch` supports GPU acceleration, which allows for faster training and inference of neural networks. This is particularly important when working with large datasets or complex models.

**Autograd**: `Pytorch` provides an automatic differentiation system called `Autograd`, which allows for easy computation of gradients. This is essential for training neural networks using backpropagation.

**Distributed Training**: `Pytorch` supports distributed training, which allows for training large models across multiple GPUs or even multiple machines. This can significantly reduce the time required to train complex models.

<hr>
<hr>

## **Tensors**

Just like we've other data structures like `arrays`, `lists`, `dataframes`, etc. Each data structure has its own use case. For example, `arrays` are used for numerical computations, `lists` are used for storing collections of items, and `dataframes` are used for tabular data. 

In similar fashion, `tensors` is a specialized multi-dimensional array designed for mathematical and computational tasks.

> Note: Here we are talking about `Tensors` in the context of `Computation`. Actually, `Tensor` is a general term used in mathematics and physics to describe a geometric object that generalizes scalars, vectors, and matrices to higher dimensions and remains consistent under coordinate transformations. 

In `PyTorch`, a `Tensor` is just a multi-dimensional array that can be used to represent data in various forms, such as images, text, and audio.

<hr>

### **Understanding Tensors with Real World Examples**

**Zero Dimensional Tensor (Scalar)**: A zero-dimensional tensor does not have a direction or orientation. It is simply a single value, like a number. For example, the `temperature` at a specific location can be represented as a zero-dimensional tensor i.e. `30` which represents the temperature in degrees Celsius.

**One Dimensional Tensor (Vector)**: A one-dimensional tensor has a direction and can be represented as a list of values. For example, the `daily temperatures` for a week can be represented as a one-dimensional tensor i.e. `[30, 32, 28, 31, 29, 27, 33]`.

**Two Dimensional Tensor (Matrix)**: A two-dimensional tensor has two directions and can be represented as a table of values. For example, the `pixel values` of a grayscale image can be represented as a two-dimensional tensor, where each value represents the intensity of the pixel i.e. `[[255, 255, 255], [0, 0, 0], [255, 255, 255]]` which represents a simple black and white image.

**Three Dimensional Tensor**: A three-dimensional tensor has three directions and can be represented as a cube of values. For example, the `RGB pixel values` of a color image can be represented as a three-dimensional tensor, where each value represents the intensity of the red, green, and blue channels i.e. `[[[255, 0, 0], [0, 255, 0], [0, 0, 255]], [[255, 255, 0], [255, 0, 255], [0, 255, 255]], [[255, 255, 255], [128, 128, 128], [0, 0, 0]]]` which represents a simple color image. Whose shape is `(3, 3, 3)` where the first dimension represents the color channels (R, G, B), the second dimension represents the height of the image, and the third dimension represents the width of the image.

<img src="../Notes_Images/3d_tensor.png" alt="3D Tensor" width="600">

**Four Dimensional Tensor**: A four-dimensional tensor has four directions and can be represented as a hypercube of values. For example, a `batch of RGB images` can be represented as a four-dimensional tensor, where each value represents the intensity of the red, green, and blue channels for each image in the batch i.e. `[[[[255, 0, 0], [0, 255, 0], [0, 0, 255]], [[255, 255, 0], [255, 0, 255], [0, 255, 255]], [[255, 255, 255], [128, 128, 128], [0, 0, 0]]], [[[255, 0, 0], [0, 255, 0], [0, 0, 255]], [[255, 255, 0], [255, 0, 255], [0, 255, 255]], [[255, 255, 255], [128, 128, 128], [0, 0, 0]]]]` which represents a batch of two color images. Whose shape is `(2, 3, 3, 3)` where the first dimension represents the batch size (number of images), the second dimension represents the color channels (R, G, B), the third dimension represents the height of the image and the fourth dimension represents the width of the image.

<img src="../Notes_Images/4d_tensor.png" alt="4D Tensor" width="600">

**Five Dimensional Tensor**: A five-dimensional tensor has five directions and can be represented as a hypercube of values. For example, a `batch of video frames` can be represented as a five-dimensional tensor, where each value represents the intensity of the red, green, and blue channels for each frame in the video. It represents a batch of two videos with three frames each. Whose shape is `(2 ,3 ,3 ,3 ,3)` where the first dimension represents the batch size (number of videos), the second dimension represents the number of frames in each video (number of images), the third dimension represents the color channels (R ,G ,B), the fourth dimension represents the height of the image and the fifth dimension represents the width of the image.

<hr>

**But why use Tensors?**

- With tensors we can represent real world data such as `Images`, `Text`, `Audio`, etc. in a format that can be easily processed by machine learning models.

- As tensors are `Multi-Dimensional Arrays` or `Matrices` and `GPU` is optimized for performing operations on matrices, using tensors allows us to take advantage of GPU acceleration for faster training and inference of machine learning models.

<hr>

## **Tensor Implementation in `Pytorch`**

In [3]:
import torch

# Version
torch.__version__

'2.6.0+cpu'

In [4]:
if torch.cuda.is_available():
  print("Torch is available, We can use GPU")
else:
  print("GPU is not available, using CPU")

GPU is not available, using CPU


## **Creating Tensors**

In [9]:
# using empty
a = torch.empty(1,2)

In [11]:
# check type
type(a)

torch.Tensor

In [14]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
# using ones
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
# using rand (Between 0 to 1)
torch.rand(2,3)

tensor([[0.3404, 0.5632, 0.8639],
        [0.6735, 0.2444, 0.0849]])

In [21]:
# using seed (Consistent Random Values)
torch.manual_seed(42)
torch.rand(2,3)


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])